### PR TITLE
Update code-of-conduct.md

### PR DESCRIPTION
**Pull request by Smitholi67**
Corrected link from CNCF Code of Conduct to LF's Code of Conduct.

### CODE REVIEW

**Review by svteb — APPROVED** [review]
lgtm

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by kosstennbl — APPROVED** [review]
LGTM

**Review by collivier — COMMENTED** [review]
@Smitholi67 CNTI is written in main page https://lfnetworking.org/cloud-native-telecom-initiative. I would also suggest to avoid the wiki links as much as we can because our wikis have moved so much for the last years.

else this PR lgtm

**Pull request merged**
