### PR TITLE
Add possibility to change node drain duration

### PR DESCRIPTION
**Pull request by martin-mat**
Add possibility to change duration of node drain
litmus chaos test. This is needed for CNFs with
longer startup/shutdown.
Additionally, fix litmus waiter code and timeout module. Slight refactor of LitmusManager module.

Refs: #2098

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Comment by martin-mat** [comment]
image

**Review by kosstennbl — APPROVED** [review]
Approve,
Not sure i fully agree with additional level of abstraction brought by get_status_info_until, i'd rather design tests around usage of get_status_info. On the other hand - i don't see anything bad with current solution so i consider this a matter of taste.
Otherwise - good change: fixes an issue with timeouts, allows suiting node drain duration to your system capabilities and CNF size, nice refactor of litmus manager.

**Review by collivier — APPROVED** [review]

**Review by rich-l — APPROVED** [review]
lgtm

**Review by svteb — APPROVED** [review]
LGTM, good abstraction of common code (considering the constraints 😄 ).

**Pull request merged**
