### PR TITLE
deletion: delete spec/workload/scalability_spec.cr

### PR DESCRIPTION
**Pull request by barmull**
## Description
Deleted scalability.cr as test group does not exist anymore.

## Issues:
Refs: #1960 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by taylor — APPROVED** [review]
lgtm

**Review by agentpoyo — APPROVED** [review]
LGTM

**Comment by barmull** [comment]
It might break github actions, because scalability test was being skipped. Is it checked?

**Comment by agentpoyo** [comment]
> It might break github actions, because scalability test was being skipped. Is it checked?

There are no actual tests tagged with `scalability`. I believe this was changed to another category after the categories were revamped for the certification to simplify the tests categories.

**Comment by agentpoyo** [comment]
When I run:

```
$ ./cnf-testsuite scalability
Task scalability was not found
```

There are no tests or tasks assigned to `scalability`. We should merge the fix in case we tag future tests as scalability or remove entirely. @taylor @wavell @denverwilliams @HashNuke

**Comment by taylor** [comment]
@wavell remove or merge?

**Review by wavell — APPROVED** [review]

**Comment by kosstennbl** [comment]
IMO, scalability_spec.cr should be deleted completely (as test group doesn't exist anymore).

The test is supposed to test increase_decrease_capacity cnf-test from compatibility category.
In compatibility_spec.cr, this spec test is absent, but it is present in configuration_spec.cr (seemingly - misplaced there).

Proposed steps:

1. In this pull request - delete scalability_spec.cr completely.
2. Create new issue to move spec for increase_decrease_capacity from configuration_spec.cr to compatibility_spec.cr

**Comment by martin-mat** [comment]
lgtm

**Pull request merged**
