### PR TITLE
Enhancement: Add test name before and after the test in console output

### PR DESCRIPTION
**Pull request by kosstennbl**
Add information of which test is starting to the console output 
Add test name to test result console output

## Issues:
Refs: #1958

No documentation update is needed.
Only outputs have been modified, functionality shouldn't be affected in any way.

### CODE REVIEW

**Review by HashNuke — CHANGES_REQUESTED** [review]
@kosstennbl Have you tried running the automated tests to check if they pass?

Quite a lot of the automated tests depend on assertions which use the pass/fail message. They would have to be updated appropriately.

Screenshot below is an example:

CleanShot 2024-04-11 at 10 20 24@2x

**Comment by kosstennbl** [comment]
Waits for merge of #1954
Then messages should be redesigned with \[[^\n]*\] inside regex

**Comment by agentpoyo** [comment]
Please create WIP or DRAFT PRs as DRAFT's when creating, this will prevent any accidental merges as "Draft" status will grey out the "merge" button until they're actually ready for review and merging.

**Comment by HashNuke** [comment]
I've changed the status of this PR to draft to reflect the title.

**Comment by kosstennbl** [comment]
Ready to test, not a draft anymore.
@HashNuke 

Btw, i can't change status from draft to open (probably insufficient permissions)

**Review by taylor — APPROVED** [review]
+1 lgtm

Note/Warning: the new regex in the specs using .* has had issues in the past with multiline PASS/FAIL output and incorrect results.

cc: @wavell @denverwilliams

**Comment by HashNuke** [comment]
@kosstennbl I held back on this PR because the main branch builds were broken.

I've made some fixes to the kubescape issues in the `kubescape-version-check` branch. The build is green. So the changes should be merged into main branch anytime soon. It might introduce some conflicts because some automated tests and specs were updated.

**Comment by kosstennbl** [comment]
@HashNuke
Ok, sure, I'll try to resolve conflicts as soon as possible

**Comment by HashNuke** [comment]
@kosstennbl Quick update - #2004 has been merged into main. This PR is now showing 2 conflicts.

**Comment by kosstennbl** [comment]
@HashNuke Rebase done, please run tests.

**Comment by HashNuke** [comment]
@kosstennbl There are two failing tags in the build - https://github.com/cnti-testcatalog/testsuite/actions/runs/8860425833/job/24331957328

* `platform:security` - The spec for `exposed_dashboard` has been removed in main. It still exists in your branch.
* `task_runner`

**Comment by HashNuke** [comment]
For anyone else curious what the output now looks like with this PR, I just ran the workload test for a sample CNF. Screenshot below. LGTM.

CleanShot 2024-04-27 at 21 20 13@2x

**Comment by kosstennbl** [comment]
@HashNuke Fixed task_runner (checked localy - it passed), deleted exposed_dashboard.
Please retest

**Comment by HashNuke** [comment]
Build passing - https://github.com/cnti-testcatalog/testsuite/actions/runs/8861261394

Will wait for the main branch build to pass before merging this PR.

**Pull request merged**
