### PR TITLE
Adapt cert tests for CNTI certification V2.0

### PR DESCRIPTION
**Pull request by martin-mat**
Ref: #1931
Ref: #1932

## Description
(name of issue/change)

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by HashNuke — APPROVED** [review]
LGTM ~! 👍

**Comment by HashNuke** [comment]
PR looks good. Triggered a build here - https://github.com/cnti-testcatalog/testsuite/actions/runs/8524764982

**Comment by martin-mat** [comment]
Updated, tested by executing cert tests.
Ready for review and potential merge, github actions can be run.

**Review by agentpoyo — APPROVED** [review]
LGTM - Need to verify github actions all clean before we merge. Once another actions finishes, I'll rerun the failed jobs for this one that Akash pushed.

**Comment by HashNuke** [comment]
I triggered a build with the new changes from this PR.

The `cnf-config` tag specs are failing.

https://github.com/cnti-testcatalog/testsuite/actions/runs/8596519498

**Comment by HashNuke** [comment]
New build running here - https://github.com/cnti-testcatalog/testsuite/actions/runs/8615039901

**Comment by HashNuke** [comment]
Looks like I wasn't pushing the latest changes for previous build.
I made a new branch and pushed the changes again. The build is running here - https://github.com/cnti-testcatalog/testsuite/actions/runs/8616979925

**Pull request merged**
