### PR TITLE
Add default kubeconfig path if KUBECONFIG is unset

### PR DESCRIPTION
**Pull request by macaktom**
## Description
Added default kubeconfig path (~/.kube/config). Added logic so KUBECONFIG is set with default kubeconfig path, if KUBECONFIG was previously unset.

## Issues:
Refs: #1422

## How has this been tested:
Tested by running all workload tests in following scenarios:
1) set KUBECONFIG with custom path
2) unset KUBECONFIG, but default kubeconfig path exists.
3) unset KUBECONFIG, default kubeconfig path doesn't exist.

Run all spec tests

## Types of changes:
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by HashNuke — APPROVED** [review]
LGTM ~! 👍

Thank you for this PR. This should fix the testsuite for cloud provider's k8s environments where kubeconfig has a predefined path.

**Comment by HashNuke** [comment]
@macaktom Could you please update this PR with the latest changes from the main branch to ensure the build is green before we merge?

Thanks.

**Comment by macaktom** [comment]
@HashNuke Ok, I updated ensure-kubeconfig branch with latest changes from main branch.

**Comment by agentpoyo** [comment]
I've checked out the branch and pushed up to verify github actions are good before we proceed in merging.

**Review by agentpoyo — APPROVED** [review]
LGTM, passing github spec tests without issues.

**Pull request merged**
