### PR TITLE
helm-install: Make helm install failure fatal

### PR DESCRIPTION
**Pull request by kosstennbl**
## Description
Currently, when helm install fails, testsuite still waits for resources and only fails on timeout.
Fix helm behavior and make it exit right after installation failure.

### CODE REVIEW

**Comment by martin-mat** [comment]
Spec tests need adaptation
https://github.com/cnti-testcatalog/testsuite/actions/runs/10455212865/job/28983108223

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by Smitholi67 — APPROVED** [review]
lgtm

**Review by svteb — APPROVED** [review]
lgtm

**Review by collivier — APPROVED** [review]

**Pull request merged**
