### PR TITLE
Bump kubectl_client to fix labelling issue

### PR DESCRIPTION
**Pull request by martin-mat**
Refs: #2062

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Comment by martin-mat** [comment]
tested:
https://github.com/cnti-testcatalog/testsuite/actions/runs/9616958098

**Review by electrocucaracha — APPROVED** [review]
The [new version](https://github.com/cnf-testsuite/kubectl_client/releases/tag/v1.0.7) has been created

**Review by horecoli — APPROVED** [review]
lgtm, but what about conflict in shards, where other libraries used this kubectl_client? Is it somehow fixed?

**Comment by martin-mat** [comment]
> what about conflict in shards, where other libraries used this kubectl_client? Is it somehow fixed?

Right version of kubectl_client is installed, see below.
shards.yml anywhere in libs does not prevent it (dependencies states just a lowest version) and it looks shards.lock is taken only from primary repo, not from libs (or at least shards gives it higher priority than those in libs)

```
shards --without-development install
Resolving dependencies
Fetching https://github.com/vulk/sam.cr.git
Fetching https://github.com/icyleaf/halite.git
Fetching https://github.com/crystal-community/icr.git
Fetching https://github.com/icyleaf/totem.git
Fetching https://github.com/sija/retriable.cr.git
Fetching https://github.com/mrrooijen/commander.git
Fetching https://github.com/cnf-testsuite/tar.git
Fetching https://github.com/cnf-testsuite/find.git
Fetching https://github.com/cnf-testsuite/git.git
Fetching https://github.com/cnf-testsuite/docker_client.git
Fetching https://github.com/cnf-testsuite/kubectl_client.git
Fetching https://github.com/cnf-testsuite/cluster_tools.git
Fetching https://github.com/cnf-testsuite/kernel_introspection.git
Fetching https://github.com/cnf-testsuite/k8s_kernel_introspection.git
Fetching https://github.com/cnf-testsuite/k8s_netstat.git
Fetching https://github.com/cnf-testsuite/helm.git
Fetching https://github.com/cnf-testsuite/release_manager.git
Fetching https://github.com/jeromegn/protobuf.cr.git
Fetching https://github.com/icyleaf/popcorn.git
Fetching https://github.com/crystal-lang/crystal-readline.git
Shard "kubectl_client" version (1.0.6) doesn't match tag version (1.0.7)
Shard "kubectl_client" version (1.0.6) doesn't match tag version (1.0.7)
Shard "kubectl_client" version (1.0.6) doesn't match tag version (1.0.7)
Shard "cluster_tools" version (1.0.0) doesn't match tag version (1.0.5)
Using sam (0.4.0 at 4e3b271)
Using readline (0.1.1 at 69ecf33)
Using icr (0.9.0 at f62bfcd)
Using commander (0.4.0)
Using retriable (0.2.5)
Using popcorn (0.3.0)
Using totem (0.7.0)
Using git (1.0.0)
Using kernel_introspection (0.1.0)
Using docker_client (1.0.0)
Using kubectl_client (1.0.7)
Using cluster_tools (1.0.5)
Using k8s_kernel_introspection (1.0.2)
Using halite (0.12.1)
Using find (0.1.0 at 129096c)
Using tar (0.1.0 at ae9bbea)
Using helm (1.0.2)
Using k8s_netstat (1.0.0)
Using release_manager (0.1.0 at a1d7b35)
Using airgap (0.1.0 at utils/airgap)
Using protobuf (2.3.0)
Writing shard.lock
```

**Review by kosstennbl — APPROVED** [review]
lgtm, thanks for the explanation above

**Pull request merged**
