### PR TITLE
fix: Change Helm library to CNFInstall module

### PR DESCRIPTION
**Pull request by barmull**
## Description
- affect CNFs that installing method is HelmDirectory
- CNFs are correctly install into cnf-default namespace (if helm_install_namespace variable is not set)
- change Helm::InstallMethod::HelmDirectory to CNFInstall::InstallMethod::HelmDirectory

## Issues:
Refs: #2039

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [X] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Comment by martin-mat** [comment]
needs rebasing

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by rich-l — APPROVED** [review]
lgtm

**Comment by martin-mat** [comment]
oran spec tests pass, but they don't work correctly. In fact they should fail, because waiting for CNFs to be deployed does not finish:
image

**Comment by martin-mat** [comment]
lgtm also now after fixing all issues. Great that all that those tests dependent on default namespaces were identified and fixed.

**Pull request merged**
