### PR TITLE
Update Kind and its image versions in gates

### PR DESCRIPTION
**Pull request by collivier**
## Description

It updates Kind from v0.17.0 to v0.22.0 and the hardcoded v1.23.13 images to v1.23.17.

## Issues:
Refs: #1886

### CODE REVIEW

**Comment by agentpoyo** [comment]
> @HashNuke @taylor et al. Could you please trigger workflow to see what to do next here ?

Once we get our published release working on merges, we can test this and push it through if there are no issues verifying and testing.

**Comment by HashNuke** [comment]
I triggered a build earlier today. I see issues in the build about not being able to get a login shell. My hunch is this is happening because the image used is based on distroless, so we might have to identify a version of the kind k8s image that isn't using distroless.

**Comment by HashNuke** [comment]
@collivier  Could you please update this PR with the latest changes from the main branch? That should fix any build issues that aren't related to this PR.

Thanks.

**Review by HashNuke — APPROVED** [review]
Changes LGTM ~! 👍
Let me push this PR as a branch and see how the GitHub Actions build runs.

**Review by HashNuke — CHANGES_REQUESTED** [review]
There are 3 automated tests for the security category failing in the builds. I've run them twice to confirm that these aren't random failures.

https://github.com/cnti-testcatalog/testsuite/actions/runs/8140376196/job/22256866814
https://github.com/cnti-testcatalog/testsuite/actions/runs/8140376196/job/22253010555

Please look into these failures to help take this PR forward.

**Comment by collivier** [comment]
@HashNuke yes I will have a look

**Comment by collivier** [comment]
PR updated as asked.

@HashNuke  could you please trigger a build as before to check vs latest changes. Thank you in advance.

**Comment by collivier** [comment]
Related to https://github.com/cnti-testcatalog/testsuite/commit/c0b0ddc83e4bc4d6a632811b8a6f02644bb0abf9 

```
Failures:

  1) Security 'non_root_user' should pass with a non-root cnf
     Failure/Error: (/Root user not found/ =~ response_s).should_not be_nil

       Expected: nil not to be nil

     # spec/workload/security_spec.cr:13

  2) Security 'non_root_user' should fail with a root cnf
     Failure/Error: (/Root user found/ =~ response_s).should_not be_nil

       Expected: nil not to be nil

     # spec/workload/security_spec.cr:27

  3) Security 'non_root_user' should fail with a root cnf using a non-default namespace
     Failure/Error: (/Root user found/ =~ response_s).should_not be_nil

       Expected: nil not to be nil

     # spec/workload/security_spec.cr:41
```


Would you mind manually triggering verification please ? It was rebased on top of main and then now includes https://github.com/cnti-testcatalog/testsuite/commit/c0b0ddc83e4bc4d6a632811b8a6f02644bb0abf9

**Review by agentpoyo — APPROVED** [review]
LGTM and passing github [actions](https://github.com/cnti-testcatalog/testsuite/actions/runs/8562825382)

**Pull request merged**
