### PR TITLE
Remove -ti in docker and kubectl calls

### PR DESCRIPTION
**Pull request by collivier**
## Description

It avoids passing stdin to the container when useless.
Please note it removes a couple of issues highlighted by [1] in airgap specs.

It also removes all useless blank chars in the files modified by this change.

[1] https://github.com/cnti-testcatalog/testsuite/pull/1949

## How has this been tested:
 - [X] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [X] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [X] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

### CODE REVIEW

**Comment by collivier** [comment]
@HashNuke would you mind running the specs in your branch. I ran a few specs locally but this change requires a full verification. Thank you in advance.

**Review by martin-mat — APPROVED** [review]
lgtm

**Comment by HashNuke** [comment]
Build passing - https://github.com/cnti-testcatalog/testsuite/actions/runs/8769450532

**Comment by HashNuke** [comment]
Resolved conflict by commenting out airgap specs as in main branch.

**Pull request merged**
