### PR TITLE
Removing single process type test from the essentials

### PR DESCRIPTION
**Pull request by CsatariGergely**
## Description
Removing single process type test from the essentials

## Issues:
Refs: [#cnf-wg/issues/242](https://github.com/cncf/cnf-wg/issues/242)

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [X] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [?] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by agentpoyo — CHANGES_REQUESTED** [review]
If this is to no longer be an essential test, it needs to be categorized as another type of test if it's going to be included with `cert`, eg. `normal` or `bonus`.

**Comment by CsatariGergely** [comment]
> If this is to no longer be an essential test, it needs to be categorized as another type of test if it's going to be included with `cert`, eg. `normal` or `bonus`.

I would put it to bonus.

**Comment by lixuna** [comment]
ref https://github.com/cncf/cnf-testsuite/issues/1795

**Comment by taylor** [comment]
certification items can be discussed in https://github.com/lfn-cnti/certification

**Pull request closed without merging**
