### PR TITLE
Fix: Routed logs test now correctly checks if CNF is being tailed

### PR DESCRIPTION
**Pull request by svteb**
## Description
Fixed two issues regarding routed_logs and fluent family of functions as described in referenced issues. Nearly everything was refactored, but all the install/uninstall and tailing functions have been manually tested and the spec tests are passing as well. Main reasons for the refactor were shortening the code and removing duplicates.

As for the refactors, the CONFIG variable does not look all that pretty but I could not figure out a better way to achieve the modularity.

## Issues:
Refs: #2025 #2016 

## How has this been tested:
 - [x] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
    * [x] Minikube cluster
 - [ ] Have not tested

## Types of changes:
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.
- [x] Maybe, I'll have to check.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [x] Tasks in issue are checked off

### CODE REVIEW

**Comment by taylor** [comment]
re-running specs after runners restored

**Review by martin-mat — APPROVED** [review]
lgtm

**Comment by horecoli** [comment]
LGTM, good job 👍

**Comment by martin-mat** [comment]
gh actions passed
https://github.com/cnti-testcatalog/testsuite/actions/runs/9439225077

**Pull request merged**
