### PR TITLE
Docs: Relocate alpha_k8s_apis to configuration sections across docs

### PR DESCRIPTION
**Pull request by svteb**
## Description
Should move all k8s API related stuff to the correct configuration sections across doc files.

Interestingly there were as of yet unimplemented TO DO'S in USAGE.md and TEST_CATEGORIES.md which were also moved for future coherence (these relate to the k8s APIs category).

## Issues:
Refs: #2077 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [x] Tasks in issue are checked off

### CODE REVIEW

**Comment by svteb** [comment]
I am not sure if I covered all the doc files, if I missed something write a comment.

**Review by collivier — APPROVED** [review]

**Comment by svteb** [comment]
I will probably rebase after #2089 is merged to avoid some issues.

**Comment by kosstennbl** [comment]
Can be rebased now

**Comment by kosstennbl** [comment]
It seems that for alpha_k8s_apis test in current documentation - can be quite easily moved (in docs and TOC).
TODOs are a different problem, they can be somehow represented in description of configuration test (they were lost during transfer to new docs)

**Review by kosstennbl — APPROVED** [review]
LGTM

**Review by collivier — APPROVED** [review]

**Review by rich-l — APPROVED** [review]
lgtm

**Review by Smitholi67 — APPROVED** [review]
lgtm

**Pull request merged**
