### PR TITLE
cert: remove cert tag from non-essential tests

### PR DESCRIPTION
**Pull request by kosstennbl**
## Description
Certification was updated to count only for essential tests. 
This commit reflects the change in certification.

## Issues:
Refs: #2117

### CODE REVIEW

**Comment by martin-mat** [comment]
just to document: "bonus tests should not be includded in the maximum points when a failure occurs" removed because:
- with current points.yml does not make sense
- the test does not make a good sense anyway (checking total number of tests)
Thus removing the spec test.

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by rich-l — APPROVED** [review]
lgtm

**Review by svteb — APPROVED** [review]
lgtm

**Pull request merged**
