### PR TITLE
Modularize implementation of tests #1861

### PR DESCRIPTION
**Pull request by martin-mat**
## Description
Modularized test im plementation:
- centralized test result output
- remove repeated code/strings/emojis from test implementation
- category emojis are taken based on test category in points.yml

- the adaptations require adaptation (simplification and removal of code) of every test case.
- This is a WIP pull request for purpose of review of the chanegs. Only test cases in workload/observability.cr are adapted. What is missing is to adapt all remaining tests (after this one goes through the review process to avoid changing many files during the review). Do not merge for now.
- note that it was also required to fix some of #1864 as the code stopped working after adding arguments to some methods.
- also note that ResultStatus enum was moved 2 levels up in hierarchy to be better usable.

## Issues:
Refs: #1861 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

### CODE REVIEW

**Review by HashNuke — APPROVED** [review]
LGTM 👍

A suggestion we could take up later: Move the test-specific emojis for tests to the points.yml file since test name and category is also maintained there.

**Comment by HashNuke** [comment]
@martin-mat  Could you please update this PR with the latest changes from the main branch and resolve conflicts? Merging latest main would also fix any build issues that aren't related to this PR.

Thanks.

**Review by agentpoyo — APPROVED** [review]
LGTM, https://github.com/cnti-testcatalog/testsuite/actions/runs/8067488377 is passing github actions as well. If you create a pull request, we can verify and this should close out #1867

**Comment by HashNuke** [comment]
Merging since build is passing when pushed from a branch in the repo - https://github.com/cnti-testcatalog/testsuite/actions/runs/8067488377

**Pull request merged**
