### PR TITLE
manifest_install: Move manifest install to repo

### PR DESCRIPTION
**Pull request by kosstennbl**
## Description
Problem explained in referenced issue.

Move "installation methods" enum from helm repo
Move Manifest-related functionality ("Manifest" module) from helm repo

## Issues:
Refs: #2105

### CODE REVIEW

**Comment by kosstennbl** [comment]
Should be merged first, then respective changes (removals) are needed to be done in Helm repo.

**Review by martin-mat — APPROVED** [review]
lgtm

**Review by svteb — APPROVED** [review]
LGTM

**Review by rich-l — APPROVED** [review]
lgtm

**Pull request merged**
